- name: Install Node Exporter for servers
  hosts:
  - prom
  vars:
    local_node_exporter_package: /data/ops/packages/prometheus/node_exporter-1.3.1.linux-amd64.tar.gz
    remote_node_exporter_dir: /data/PRG
  tasks:
  - name: Create Directory for servers
    ansible.builtin.file:
      path: '{{ remote_node_exporter_dir }}'
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      state: directory
      recurse: yes
  - name: 'Unarchive Node Exporter Packages to {{ remote_node_exporter_dir }}'
    ansible.builtin.unarchive:
      src: '{{ local_node_exporter_package }}'
      dest: '{{ remote_node_exporter_dir }}'
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      list_files: yes
    register: archive_contents
  - name: 'Delete old unpack Directory {{ remote_node_exporter_dir }}/node_exporter'
    ansible.builtin.file:
      path: '{{ remote_node_exporter_dir }}/node_exporter'
      state: absent
  - name: 'Rename Unpack Directory to {{ remote_node_exporter_dir }}/node_exporter'
    ansible.builtin.shell: 'mv {{ remote_node_exporter_dir }}/{{archive_contents.files[0][:-1]}} {{ remote_node_exporter_dir }}/node_exporter'
  - name: Create Node Exporter Service for servers
    ansible.builtin.shell: |
      echo '[Unit]
      Description=node_exporter
      Documentation=https://prometheus.io/
      After=network.target
      StartLimitIntervalSec=0
      
      [Service]
      Type=simple
      User={{ ansible_user }}
      Group={{ ansible_user }}
      ExecStart={{ remote_node_exporter_dir }}/node_exporter/node_exporter
      Restart=on-failure
      
      [Install]
      WantedBy=multi-user.target' > /usr/lib/systemd/system/node_exporter.service
  - name: Reload node_exporter.service
    ansible.builtin.shell: systemctl daemon-reload
  - name: Restart node_exporter.service and enable it
    ansible.builtin.service:
      name: node_exporter.service
      enabled: yes
      state: restarted
